0: 'Not Available'
1: 'Reserved'
2: 'Reserved'
3: 'Reserved'
4: 'Reserved'
5: 'Reserved'
6: 'Reserved'
7: 'Reserved'
8: 'Reserved'
9: 'Reserved'
10: 'Reserved'
11: 'Reserved'
12: 'Reserved' 
13: 'Reserved'
14: 'Reserved'
15: 'Reserved'
16: 'Reserved'
17: 'Reserved'
18: 'Reserved'
19: 'Reserved'
20: 'Wing in ground'
21: 'Wing in ground'
22: 'Wing in ground'
23: 'Wing in ground'
24: 'Wing in ground'
25: 'Wing in ground'
26: 'Wing in ground'
27: 'Wing in ground'
28: 'Wing in ground'
29: 'Wing in ground'
30: 'Fishing'
31: 'Towing'
32: 'Towing'
33: 'Dredging ro underwater ops'
34: 'Diving ops'
35: 'Military ops'
36: 'Sailing'
37: 'Pleasure Craft'
38: 'Reserved'
39: 'Reserved'
40: 'High speed craft'
41: 'High speed craft'
42: 'High speed craft'
43: 'High speed craft'
44: 'High speed craft'
45: 'High speed craft'
46: 'High speed craft'
47: 'High speed craft'
48: 'High speed craft'
49: 'High speed craft'
50: 'Pilot vessel'
51: 'Search and Rescue vessel'
52: 'Tug'
53: 'Port Tender'
54: 'Anti-pollution equipment'
55: 'Law Enforcement'
56: 'Spare - Local Vessel'
57: 'Spare - Local Vessel'
58: 'Medical Transport'
59: 'Noncombatant ship according to RR Resolution No. 18'
60: 'Passenger'
61: 'Passenger'
62: 'Passenger'
63: 'Passenger'
64: 'Passenger'
65: 'Passenger'
66: 'Passenger'
67: 'Passenger'
68: 'Passenger'
69: 'Passenger'
70: 'Cargo'
71: 'Cargo'
72: 'Cargo'
73: 'Cargo'
74: 'Cargo'
75: 'Cargo'
76: 'Cargo'
77: 'Cargo'
78: 'Cargo'
79: 'Cargo'
80: 'Tanker'
81: 'Tanker'
82: 'Tanker'
83: 'Tanker'
84: 'Tanker'
85: 'Tanker'
86: 'Tanker'
87: 'Tanker'
88: 'Tanker'
89: 'Tanker'
90: 'Other Type'
91: 'Other Type'
92: 'Other Type'
93: 'Other Type'
94: 'Other Type'
95: 'Other Type'
96: 'Other Type'
97: 'Other Type'
98: 'Other Type'
99: 'Other Type'
100: 'Navigation Aid'
101: 'Reference Point'
102: 'RACON'
103: 'Offshore Structure'
104: 'Spare'
105: 'Light, without Sectors'
106: 'Light, with Sectors'
107: 'Leading Light Front'
108: 'Leading Light Rear'
109: 'Beacon, Cardinal N'
110: 'Beacon, Cardinal E'
111: 'Beacon, Cardinal S'
112: 'Beacon, Cardinal W'
113: 'Beacon, Port Hand'
114: 'Beacon, Starboard Hand'
115: 'Beacon, Preferred Channel Port hand'
116: 'Beacon, Preferred Channel Starboard hand'
117: 'Beacon, Isolated danger'
118: 'Beacon, Safe Water'
119: 'Beacon, Special Mark'
120: 'Cardinal Mark N'
121: 'Cardinal Mark E'
122: 'Cardinal Mark S'
123: 'Cardinal Mark W'
124: 'Port Hand Mark'
125: 'Starboard Hand Mark'
126: 'Preferred Channel Port Hand'
127: 'Preferred Channel Starboard Hand'
128: 'Isolated Danger'
129: 'Safe Water'
130: 'Manned VTS'
131: 'Light Vessel'
132: 'Regional vessel'
133: 'Regional vessel'
134: 'Regional vessel'
135: 'Regional vessel'
136: 'Regional vessel'
137: 'Regional vessel'
138: 'Regional vessel'
139: 'Regional vessel'
140: 'Regional vessel'
141: 'Regional vessel'
142: 'Regional vessel'
143: 'Regional vessel'
144: 'Regional vessel'
145: 'Regional vessel'
146: 'Regional vessel'
147: 'Regional vessel'
148: 'Regional vessel'
149: 'Regional vessel'
150: 'Regional vessel'
151: 'Regional vessel'
152: 'Regional vessel'
153: 'Regional vessel'
154: 'Regional vessel'
155: 'Regional vessel'
156: 'Regional vessel'
157: 'Regional vessel'
158: 'Regional vessel'
159: 'Regional vessel'
160: 'Regional vessel'
161: 'Regional vessel'
162: 'Regional vessel'
163: 'Regional vessel'
164: 'Regional vessel'
165: 'Regional vessel'
166: 'Regional vessel'
167: 'Regional vessel'
168: 'Regional vessel'
169: 'Regional vessel'
170: 'Regional vessel'
171: 'Regional vessel'
172: 'Regional vessel'
173: 'Regional vessel'
174: 'Regional vessel'
175: 'Regional vessel'
176: 'Regional vessel'
177: 'Regional vessel'
178: 'Regional vessel'
179: 'Regional vessel'
180: 'Regional vessel'
181: 'Regional vessel'
182: 'Regional vessel'
183: 'Regional vessel'
184: 'Regional vessel'
185: 'Regional vessel'
186: 'Regional vessel'
187: 'Regional vessel'
188: 'Regional vessel'
189: 'Regional vessel'
190: 'Regional vessel'
191: 'Regional vessel'
192: 'Regional vessel'
193: 'Regional vessel'
194: 'Regional vessel'
195: 'Regional vessel'
196: 'Regional vessel'
197: 'Regional vessel'
198: 'Regional vessel'
199: 'Regional vessel'
200: 'Reserved'
201: 'Reserved'
202: 'Reserved'
203: 'Reserved'
204: 'Reserved'
205: 'Reserved'
206: 'Reserved'
207: 'Reserved'
208: 'Reserved'
209: 'Reserved'
210: 'Reserved'
211: 'Reserved'
212: 'Reserved'
213: 'Reserved'
214: 'Reserved'
215: 'Reserved'
216: 'Reserved'
217: 'Reserved'
218: 'Reserved'
219: 'Reserved'
220: 'Reserved'
221: 'Reserved'
222: 'Reserved'
223: 'Reserved'
224: 'Reserved'
225: 'Reserved'
226: 'Reserved'
227: 'Reserved'
228: 'Reserved'
229: 'Reserved'
230: 'Reserved'
231: 'Reserved'
232: 'Reserved'
233: 'Reserved'
234: 'Reserved'
235: 'Reserved'
236: 'Reserved'
237: 'Reserved'
238: 'Reserved'
239: 'Reserved'
240: 'Reserved'
241: 'Reserved'
242: 'Reserved'
243: 'Reserved'
244: 'Reserved'
245: 'Reserved'
246: 'Reserved'
247: 'Reserved'
248: 'Reserved'
249: 'Reserved'
250: 'Reserved'
251: 'Reserved'
252: 'Reserved'
253: 'Reserved'
254: 'Reserved'
255: 'Reserved'
256: 'Reserved'
257: 'Reserved'
258: 'Reserved'
259: 'Reserved'
260: 'Reserved'
261: 'Reserved'
262: 'Reserved'
263: 'Reserved'
264: 'Reserved'
265: 'Reserved'
266: 'Reserved'
267: 'Reserved'
268: 'Reserved'
269: 'Reserved'
270: 'Reserved'
271: 'Reserved'
272: 'Reserved'
273: 'Reserved'
274: 'Reserved'
275: 'Reserved'
276: 'Reserved'
277: 'Reserved'
278: 'Reserved'
279: 'Reserved'
280: 'Reserved'
281: 'Reserved'
282: 'Reserved'
283: 'Reserved'
284: 'Reserved'
285: 'Reserved'
286: 'Reserved'
287: 'Reserved'
288: 'Reserved'
289: 'Reserved'
290: 'Reserved'
291: 'Reserved'
292: 'Reserved'
293: 'Reserved'
294: 'Reserved'
295: 'Reserved'
296: 'Reserved'
297: 'Reserved'
298: 'Reserved'
299: 'Reserved'
