South Louisiana:
    LAT:
    LON:
Houston:
    LAT:
    LON:
Newark:
    LAT:
    LON:
Beaumont:
    LAT:
    LON:
Long Beach:
    LAT:
    LON:
Hampton Roads:
    LAT:
    LON:
New Orleans:
    LAT:
    LON:
Corpus Christi:
    LAT:
    LON:
Greater Baton Rouge:
    LAT:
    LON:
Plaquemines:
    LAT:
    LON:
Los Angeles:
    LAT:
    LON:
Lake Charles:
    LAT:
    LON:
Mobile:
    LAT:
    LON:
Texas City:
    LAT:
    LON:
Huntington-Tristate:
    LAT:
    LON:
Baltimore:
    LAT:
    LON:
Duluth and Superior:
    LAT:
    LON:
Port Arthur:
    LAT:
    LON:
St. Louis and East St. Louis:
    LAT:
    LON:
Pittsburgh:
    LAT:
    LON:
Pascagoula:
    LAT:
    LON:
Tampa Bay:
    LAT:
    LON:
Savannah:
    LAT:
    LON:
Valdez:
    LAT:
    LON:
Philadelphia:
    LAT:
    LON:
Richmond:
    LAT:
    LON:
Portland(Oregon):
    LAT:
    LON:
Tacoma:
    LAT:
    LON:
Everglades:
    LAT:
    LON:
Seattle:
    LAT:
    LON:
Freeport:
    LAT:
    LON:
Oakland:
    LAT:
    LON:
Paulsboro:
    LAT:
    LON:
Chaleston:
    LAT:
    LON:
Boston:
    LAT:
    LON:
Harbors:
    LAT:
    LON:
Jacksonville:
    LAT:
    LON:
Chicago:
    LAT:
    LON:
Honolulu:
    LAT:
    LON:
Memphis:
    LAT:
    LON:
Longview:
    LAT:
    LON:
Detroit:
    LAT:
    LON:
Indiana-Burns Harbor:
    LAT:
    LON:
Portland(Maine):
    LAT:
    LON:
Marcus Hook:
    LAT:
    LON:
Cincinnati:
    LAT:
    LON:
Cleveland:
    LAT:
    LON:
Galveston:
    LAT:
    LON:
Albany-Rensselaer:
    LAT:
    LON:
Port Lavaca Point Comfort:
    LAT:
    LON:
San Juan:
    LAT:
    LON:
Anacortes:
    LAT:
    LON:
Kalama:
    LAT:
    LON:
Toledo:
    LAT:
    LON:
Barbers Point:
    LAT:
    LON:
New Haven Harbor:
    LAT:
    LON:
Burns Waterway Harbor:
    LAT:
    LON:
Presque Isle:
    LAT:
    LON:
Providence:
    LAT:
    LON:
St. Clair:
    LAT:
    LON:
Miami:
    LAT:
    LON:
New Castle:
    LAT:
    LON:
Fourchon:
    LAT:
    LON:
Lousville:
    LAT:
    LON:
Stoneport:
    LAT:
    LON:
Wilmington(North Carolina):
    LAT:
    LON:
Wilmington(Delaware):
    LAT:
    LON:
Mount Vernon:
    LAT:
    LON:
Calcite:
    LAT:
    LON:
Camden-Gloucester:
    LAT:
    LON:
Brownsville:
    LAT:
    LON:
Victoria:
    LAT:
    LON:
Vancouver:
    LAT:
    LON:
Kaskaskia:
    LAT:
    LON:
Silver Bay:
    LAT:
    LON:
Ashtabula:
    LAT:
    LON:
Conneaut:
    LAT:
    LON:
Saint Paul:
    LAT:
    LON:
Nikiski:
    LAT:
    LON:
Port Inland:
    LAT:
    LON:
Escanaba(Michigan):
    LAT:
    LON:
Kahului:
    LAT:
    LON:
Marblehead:
    LAT:
    LON:
Greenville:
    LAT:
    LON:
Stockton:
    LAT:
    LON:
Morehead City:
    LAT:
    LON:
Terrebonne:
    LAT:
    LON:
Canaveral:
    LAT:
    LON:
Brunswick:
    LAT:
    LON:
Milwaukee:
    LAT:
    LON:
Dolomite:
    LAT:
    LON:
Sandusky:
    LAT:
    LON:
Anchorage:
    LAT:
    LON:
Manatee:
    LAT:
    LON:
Tulsa Port of Catoosa:
    LAT:
    LON:
Portsmouth:
    LAT:
    LON:
Nashville:
    LAT:
    LON:
Caruthersville:
    LAT:
    LON:
